# Generated by Django 4.2.6 on 2023-10-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=255)),
                ('board_content', models.TextField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('write_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('id', models.CharField(db_column='ID', max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=45)),
                ('nickname', models.CharField(blank=True, db_column='Nickname', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=45, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_day', models.DateField()),
                ('search_cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'search',
                'managed': False,
            },
        ),
    ]
